version: "3.8"

services:
  app:
    build: .
    container_name: python_app
    restart: always
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    entrypoint: ["sh", "/app/entrypoint.sh"]
