# Generated by Django 5.2 on 2025-04-29 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vulnerability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cve_id', models.CharField(max_length=20, unique=True)),
                ('published_date', models.DateTimeField()),
                ('last_modified_date', models.DateTimeField()),
                ('severity', models.CharField(max_length=20)),
                ('fixed', models.BooleanField(default=False)),
            ],
        ),
    ]
